### ISSUE TITLE
no_std compatible

### ISSUE THREAD

**Issue by goral09** [thomcc/rust-base16#1]
Hi Thom,

How difficult it would be to make this `no_std` compatible? Looks great and I already am using it in few places but now I have a need for `no_std` compatible version.

**Comment by thomcc** [comment]
I think making it have a "std" feature that's on by default would not be hard. I'll see what I can do.

**Comment by goral09** [comment]
Thank you @thomcc .

**Comment by thomcc** [comment]
Fixed in 0.1.2. Thanks for the report.
